<?php
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);
session_start();
require_once 'db_config.php';
$conn = getDBConnection();
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) { header('Location: al_login.php'); exit(); }

$active_tab = $_GET['tab'] ?? 'alumni';
if (!in_array($active_tab, ['alumni','jobs','events'], true)) $active_tab = 'alumni';
$message = htmlspecialchars($_GET['message'] ?? '');
$messageType = htmlspecialchars($_GET['type'] ?? '');

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    if ($_POST['action'] === 'restore_alumni') { $id = (int)($_POST['alumni_id'] ?? 0); $stmt = $conn->prepare("UPDATE itcp SET status='Active' WHERE id=? AND status='archived'"); if ($stmt){$stmt->bind_param('i',$id);$stmt->execute();$stmt->close();}}
    if ($_POST['action'] === 'restore_job') { $id = (int)($_POST['job_id'] ?? 0); $stmt = $conn->prepare("UPDATE jobs SET archived=0 WHERE id=?"); if ($stmt){$stmt->bind_param('i',$id);$stmt->execute();$stmt->close();}}
    if ($_POST['action'] === 'restore_event') { $id = (int)($_POST['event_id'] ?? 0); $stmt = $conn->prepare("UPDATE events SET archived=0 WHERE id=?"); if ($stmt){$stmt->bind_param('i',$id);$stmt->execute();$stmt->close();}}
    header("Location: ad_archives.php?tab=" . urlencode($active_tab) . "&message=Item restored&type=success");
    exit();
}

$search = trim($_GET['search'] ?? '');
$limit = 20; $page = max(1, (int)($_GET['page'] ?? 1)); $start = ($page - 1) * $limit;
$total_alumni = (int)($conn->query("SELECT COUNT(*) c FROM itcp WHERE status='archived'")->fetch_assoc()['c'] ?? 0);
$total_jobs = (int)($conn->query("SELECT COUNT(*) c FROM jobs WHERE archived=1")->fetch_assoc()['c'] ?? 0);
$total_events = (int)($conn->query("SELECT COUNT(*) c FROM events WHERE archived=1")->fetch_assoc()['c'] ?? 0);
$archived_alumni = $archived_jobs = $archived_events = []; $filtered_total = 0;
if ($active_tab === 'alumni') { $w="status='archived'"; if($search!==''){ $e=$conn->real_escape_string($search); $w.=" AND (firstname LIKE '%$e%' OR lastname LIKE '%$e%' OR email LIKE '%$e%')"; } $r=$conn->query("SELECT id,firstname,lastname,email,program,year_graduated,date_joined FROM itcp WHERE $w ORDER BY date_joined DESC LIMIT $limit OFFSET $start"); if($r){while($x=$r->fetch_assoc())$archived_alumni[]=$x;} $filtered_total=(int)($conn->query("SELECT COUNT(*) c FROM itcp WHERE $w")->fetch_assoc()['c']??0);}
if ($active_tab === 'jobs') { $w="archived=1"; if($search!==''){ $e=$conn->real_escape_string($search); $w.=" AND (title LIKE '%$e%' OR company LIKE '%$e%')"; } $r=$conn->query("SELECT id,title,company,posted_date FROM jobs WHERE $w ORDER BY posted_date DESC LIMIT $limit OFFSET $start"); if($r){while($x=$r->fetch_assoc())$archived_jobs[]=$x;} $filtered_total=(int)($conn->query("SELECT COUNT(*) c FROM jobs WHERE $w")->fetch_assoc()['c']??0);}
if ($active_tab === 'events') { $w="archived=1"; if($search!==''){ $e=$conn->real_escape_string($search); $w.=" AND (title LIKE '%$e%' OR venue LIKE '%$e%')"; } $r=$conn->query("SELECT id,title,type,event_date,venue FROM events WHERE $w ORDER BY event_date DESC LIMIT $limit OFFSET $start"); if($r){while($x=$r->fetch_assoc())$archived_events[]=$x;} $filtered_total=(int)($conn->query("SELECT COUNT(*) c FROM events WHERE $w")->fetch_assoc()['c']??0);}
$total_pages = max(1, (int)ceil(max(1, $filtered_total) / $limit));
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Archives - Admin Panel</title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link href="https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;600;700&display=swap" rel="stylesheet"><style>
:root{--cr:#8b0000;--cr-dk:#600000;--cr-lt:#b91c1c;--cr-pale:#fef2f2;--border:#e8dada;--surface:#fff;--bg:#faf7f7;--muted:#7a6a6a;--ink:#1a0a0a;--shadow-sm:0 1px 4px rgba(139,0,0,.07),0 2px 12px rgba(139,0,0,.05);--r:14px}body{background:var(--bg);font-family:'Sora',sans-serif;color:var(--ink)}.page-title h1{font-size:1.5rem;font-weight:700;color:var(--ink);line-height:1.2}.page-title p{font-size:.82rem;color:var(--muted);margin-top:2px}.stat-pill{background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;padding:.75rem 1.25rem;color:var(--ink)}.admin-card{background:var(--surface);border-radius:var(--r);border:1px solid var(--border);box-shadow:var(--shadow-sm);overflow:hidden}.tab-nav{display:flex;border-bottom:1px solid var(--border)}.tab-nav a{padding:.55rem 1rem;font-size:.78rem;font-weight:600;color:var(--muted);text-decoration:none;border:1.5px solid var(--border);border-radius:100px;background:var(--surface);margin:.35rem}.tab-nav a.active,.tab-nav a:hover{color:#fff;background:var(--cr);border-color:var(--cr)}.archive-table{width:100%;border-collapse:collapse}.archive-table th{padding:.7rem 1rem;text-align:left;font-size:.65rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:var(--muted);border-bottom:1px solid var(--border);background:#f9fafb}.archive-table td{padding:.8rem 1rem;border-bottom:1px solid rgba(232,218,218,.5)}.archive-table tr:hover td{background:var(--cr-pale)}.btn-restore{background:#fff5f5;color:#7a0000;border:1px solid #fecaca;padding:.35rem .8rem;border-radius:100px;font-size:.72rem;font-weight:600}.search-input{border:1.5px solid #d1d5db;border-radius:100px;padding:.45rem .875rem .45rem 2.5rem}.search-input:focus{outline:none;border-color:var(--cr);box-shadow:0 0 0 3px rgba(139,0,0,.08)}
</style></head><body>
<?php include 'ad_header_universal.php'; ?><?php include 'ad_sidebar_universal.php'; ?>
<main class="pt-20 ml-16 min-h-screen">
<div class="max-w-7xl mx-auto px-0 mb-5"><div class="page-title"><h1>Archives</h1><p>Browse and restore archived alumni accounts, job posts, and events</p></div><div class="grid grid-cols-3 gap-3 mt-4"><div class="stat-pill"><div class="text-2xl font-bold"><?= $total_alumni ?></div><div class="text-xs text-gray-500">Archived Alumni</div></div><div class="stat-pill"><div class="text-2xl font-bold"><?= $total_jobs ?></div><div class="text-xs text-gray-500">Archived Jobs</div></div><div class="stat-pill"><div class="text-2xl font-bold"><?= $total_events ?></div><div class="text-xs text-gray-500">Archived Events</div></div></div></div>
<div class="max-w-7xl mx-auto px-4 pb-10">
<?php if ($message): ?><div class="mb-4 px-4 py-2 rounded-lg border <?= $messageType==='success'?'bg-green-50 border-green-200 text-green-700':'bg-red-50 border-red-200 text-red-700' ?>"><?= $message ?></div><?php endif; ?>
<div class="admin-card">
<div class="tab-nav"><a href="?tab=alumni" class="<?= $active_tab==='alumni'?'active':'' ?>">Alumni (<?= $total_alumni ?>)</a><a href="?tab=jobs" class="<?= $active_tab==='jobs'?'active':'' ?>">Jobs (<?= $total_jobs ?>)</a><a href="?tab=events" class="<?= $active_tab==='events'?'active':'' ?>">Events (<?= $total_events ?>)</a></div>
<div class="p-4 bg-gray-50 border-b"><form class="flex gap-2"><input type="hidden" name="tab" value="<?= $active_tab ?>"><div class="relative flex-1"><i class="fas fa-search absolute left-2.5 top-1/2 -translate-y-1/2 text-gray-400 text-xs"></i><input class="search-input w-full" name="search" value="<?= htmlspecialchars($search) ?>" placeholder="Search archived <?= $active_tab ?>..."></div><button class="px-4 py-2 text-white rounded-lg text-sm font-semibold" style="background:#7a0000">Search</button></form></div>
<div class="overflow-x-auto">
<?php if($active_tab==='alumni'): ?><table class="archive-table"><thead><tr><th>Name</th><th>Program</th><th>Batch</th><th>Email</th><th>Date Archived</th><th style="text-align:right">Action</th></tr></thead><tbody><?php if(empty($archived_alumni)): ?><tr><td colspan="6" class="text-center py-10 text-gray-400">No archived alumni.</td></tr><?php else: foreach($archived_alumni as $a): ?><tr><td class="font-semibold text-gray-900"><?= htmlspecialchars($a['firstname'].' '.$a['lastname']) ?></td><td><?= htmlspecialchars($a['program']??'—') ?></td><td><?= htmlspecialchars($a['year_graduated']??'—') ?></td><td><?= htmlspecialchars($a['email']) ?></td><td><?= $a['date_joined']?date('M d, Y',strtotime($a['date_joined'])):'—' ?></td><td style="text-align:right"><button onclick="showRestore('restore_alumni','<?= (int)$a['id'] ?>','<?= htmlspecialchars($a['firstname'].' '.$a['lastname']) ?>')" class="btn-restore"><i class="fas fa-undo text-xs"></i> Restore</button></td></tr><?php endforeach; endif; ?></tbody></table><?php endif; ?>
<?php if($active_tab==='jobs'): ?><table class="archive-table"><thead><tr><th>Job Title</th><th>Company</th><th>Date Posted</th><th style="text-align:right">Action</th></tr></thead><tbody><?php if(empty($archived_jobs)): ?><tr><td colspan="4" class="text-center py-10 text-gray-400">No archived jobs.</td></tr><?php else: foreach($archived_jobs as $j): ?><tr><td class="font-semibold text-gray-900"><?= htmlspecialchars($j['title']) ?></td><td><?= htmlspecialchars($j['company']??'—') ?></td><td><?= !empty($j['posted_date'])?date('M d, Y',strtotime($j['posted_date'])):'—' ?></td><td style="text-align:right"><button onclick="showRestore('restore_job','<?= (int)$j['id'] ?>','<?= htmlspecialchars($j['title']) ?>')" class="btn-restore"><i class="fas fa-undo text-xs"></i> Restore</button></td></tr><?php endforeach; endif; ?></tbody></table><?php endif; ?>
<?php if($active_tab==='events'): ?><table class="archive-table"><thead><tr><th>Event Title</th><th>Type</th><th>Event Date</th><th>Venue</th><th style="text-align:right">Action</th></tr></thead><tbody><?php if(empty($archived_events)): ?><tr><td colspan="5" class="text-center py-10 text-gray-400">No archived events.</td></tr><?php else: foreach($archived_events as $e): ?><tr><td class="font-semibold text-gray-900"><?= htmlspecialchars($e['title']) ?></td><td><?= htmlspecialchars($e['type']??'General') ?></td><td><?= !empty($e['event_date'])?date('M d, Y',strtotime($e['event_date'])):'—' ?></td><td><?= htmlspecialchars($e['venue']??'—') ?></td><td style="text-align:right"><button onclick="showRestore('restore_event','<?= (int)$e['id'] ?>','<?= htmlspecialchars($e['title']) ?>')" class="btn-restore"><i class="fas fa-undo text-xs"></i> Restore</button></td></tr><?php endforeach; endif; ?></tbody></table><?php endif; ?>
</div></div></div></main>
<div id="restoreModal" class="fixed inset-0 bg-slate-900/55 backdrop-blur-sm hidden items-center justify-center p-4 z-50"><div class="bg-white rounded-2xl w-full max-w-md shadow-2xl"><div class="p-6 text-center"><div class="w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-3" style="background:#fff5f5;"><i class="fas fa-undo text-lg" style="color:#7a0000;"></i></div><h3 class="text-base font-bold text-gray-900 mb-2">Restore Item</h3><p class="text-sm text-gray-500 mb-5" id="restoreModalText"></p><div class="flex justify-center gap-2"><button onclick="closeModal()" class="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg text-sm font-semibold">Cancel</button><form method="POST"><input type="hidden" name="action" id="restoreAction"><input type="hidden" name="alumni_id" id="restoreAlumniId"><input type="hidden" name="job_id" id="restoreJobId"><input type="hidden" name="event_id" id="restoreEventId"><button class="px-4 py-2 text-white rounded-lg text-sm font-semibold" style="background:#7a0000;">Restore</button></form></div></div></div></div>
<script>
function showRestore(action,id,label){document.getElementById('restoreAction').value=action;document.getElementById('restoreAlumniId').value='';document.getElementById('restoreJobId').value='';document.getElementById('restoreEventId').value='';const f=action==='restore_alumni'?'restoreAlumniId':action==='restore_job'?'restoreJobId':'restoreEventId';document.getElementById(f).value=id;document.getElementById('restoreModalText').textContent='Restore "'+label+'"? It will become active again.';document.getElementById('restoreModal').classList.remove('hidden');document.getElementById('restoreModal').classList.add('flex');}
function closeModal(){document.getElementById('restoreModal').classList.add('hidden');document.getElementById('restoreModal').classList.remove('flex');}
</script>
</body></html>
