<?php
session_start();
date_default_timezone_set('Asia/Manila');
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) { header('Location: al_login.php'); exit(); }
require_once 'db_config.php';
$conn = getDBConnection();
$conn->query("CREATE TABLE IF NOT EXISTS announcements (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,content TEXT NOT NULL,image VARCHAR(255),status ENUM('draft','published') DEFAULT 'draft',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)");
$message='';$messageType='';
$upload_dir='uploads/announcements/'; if(!file_exists($upload_dir)) mkdir($upload_dir,0777,true);
function cleanDescription($text){ if(empty($text)) return ''; $text=str_replace(['\\r\\n','\\n','\\r'],"\n",$text); return stripslashes($text); }
function handleImageUpload($file,$upload_dir){ $image=''; if(isset($file)&&$file['error']===UPLOAD_ERR_OK){ $ext=strtolower(pathinfo($file['name'],PATHINFO_EXTENSION)); if(in_array($ext,['jpg','jpeg','png','gif'])){ $new=uniqid().'.'.$ext; if(move_uploaded_file($file['tmp_name'],$upload_dir.$new)) $image=$new; }} return $image; }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['action'])){
    $action=$_POST['action'];
    if($action==='add_announcement'){ $title=$_POST['title'];$content=cleanDescription($_POST['content']);$image=handleImageUpload($_FILES['announcement_image'],$upload_dir);$status=$_POST['status'];$s=$conn->prepare("INSERT INTO announcements (title,content,image,status,created_at) VALUES (?,?,?,?,NOW())");$s->bind_param("ssss",$title,$content,$image,$status);$s->execute();$s->close();$message='Announcement added successfully!';$messageType='success'; }
    if($action==='edit_announcement'){ $id=(int)$_POST['announcement_id'];$title=$_POST['title'];$content=cleanDescription($_POST['content']);$image=handleImageUpload($_FILES['announcement_image'],$upload_dir);$status=$_POST['status']; if($image!==''){ $s=$conn->prepare("UPDATE announcements SET title=?,content=?,image=?,status=? WHERE id=?");$s->bind_param("ssssi",$title,$content,$image,$status,$id);} else {$s=$conn->prepare("UPDATE announcements SET title=?,content=?,status=? WHERE id=?");$s->bind_param("sssi",$title,$content,$status,$id);} $s->execute();$s->close();$message='Announcement updated!';$messageType='success';}
    if($action==='delete_announcement'){ $id=(int)$_POST['announcement_id'];$s=$conn->prepare("DELETE FROM announcements WHERE id=?");$s->bind_param("i",$id);$s->execute();$s->close();$message='Announcement deleted.';$messageType='success';}
    header("Location: ad_announcements.php?message=".urlencode($message)."&type=".urlencode($messageType)); exit();
}
if(isset($_GET['message'])){$message=htmlspecialchars($_GET['message']);$messageType=htmlspecialchars($_GET['type']);}
$result=$conn->query("SELECT * FROM announcements ORDER BY created_at DESC");
$totalAnn=(int)($conn->query("SELECT COUNT(*) c FROM announcements")->fetch_assoc()['c']??0);
$published=(int)($conn->query("SELECT COUNT(*) c FROM announcements WHERE status='published'")->fetch_assoc()['c']??0);
$drafts=(int)($conn->query("SELECT COUNT(*) c FROM announcements WHERE status='draft'")->fetch_assoc()['c']??0);
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Announcements - Admin Panel</title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link href="https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;600;700&display=swap" rel="stylesheet"><style>
:root{--cr:#8b0000;--cr-dk:#600000;--cr-lt:#b91c1c;--cr-pale:#fef2f2;--border:#e8dada;--surface:#fff;--bg:#faf7f7;--muted:#7a6a6a;--ink:#1a0a0a;--shadow-sm:0 1px 4px rgba(139,0,0,.07),0 2px 12px rgba(139,0,0,.05);--r:14px}body{background:var(--bg);font-family:'Sora',sans-serif;color:var(--ink)}.page-title h1{font-size:1.5rem;font-weight:700;color:var(--ink);line-height:1.2}.page-title p{font-size:.82rem;color:var(--muted);margin-top:2px}.stat-pill{background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;padding:.75rem 1.25rem;color:var(--ink)}.admin-card{background:var(--surface);border-radius:var(--r);border:1px solid var(--border);box-shadow:var(--shadow-sm);overflow:hidden}.admin-card-header{background:linear-gradient(to right,#fff5f5,#ffe4e4);border-bottom:1px solid #fecaca;padding:1rem 1.5rem;display:flex;align-items:center;justify-content:space-between}.form-input{border:1.5px solid #d1d5db;border-radius:100px;padding:.5rem .85rem;font-size:.82rem;width:100%;background:#fafafa}.form-input:focus{outline:none;border-color:var(--cr);box-shadow:0 0 0 3px rgba(139,0,0,.08);background:#fff}.btn-primary{background:var(--cr);color:#fff;padding:.5rem 1.15rem;border-radius:100px;font-size:.8rem;font-weight:600;border:none}.ann-item{display:flex;gap:1rem;padding:1rem 1.25rem;border-bottom:1px solid rgba(232,218,218,.5)}.ann-item:hover{background:var(--cr-pale)}.ann-thumb{width:64px;height:48px;border-radius:8px;overflow:hidden;background:#f3f4f6;border:1px solid var(--border);display:flex;align-items:center;justify-content:center}.ann-thumb img{width:100%;height:100%;object-fit:cover}.badge{display:inline-flex;align-items:center;padding:.2rem .6rem;border-radius:9999px;font-size:.65rem;font-weight:700}.badge-published{background:#dcfce7;color:#15803d}.badge-draft{background:#fef9c3;color:#a16207}
</style></head><body>
<?php $hide_admin_inquiries=true; include __DIR__.'/ad_header_universal.php'; ?><?php include __DIR__.'/ad_sidebar_universal.php'; ?>
<main class="pt-20 ml-16 min-h-screen"><div class="max-w-7xl mx-auto px-4 mb-5"><div class="page-title"><h1>Announcements</h1><p>Publish and manage system announcements for alumni</p></div><div class="flex justify-end mb-3"><button id="addAnnouncementBtn" class="bg-[#8b0000] text-white px-4 py-2.5 rounded-full text-sm font-semibold">New Announcement</button></div><div class="grid grid-cols-3 gap-3 mt-2"><div class="stat-pill"><div class="text-2xl font-bold"><?= $totalAnn ?></div><div class="text-xs text-gray-500">Total</div></div><div class="stat-pill"><div class="text-2xl font-bold"><?= $published ?></div><div class="text-xs text-gray-500">Published</div></div><div class="stat-pill"><div class="text-2xl font-bold"><?= $drafts ?></div><div class="text-xs text-gray-500">Drafts</div></div></div></div>
<div class="max-w-7xl mx-auto px-4 pb-10"><?php if($message): ?><div class="mb-4 px-4 py-2 rounded-lg border <?= $messageType==='success'?'bg-green-50 border-green-200 text-green-700':'bg-red-50 border-red-200 text-red-700' ?>"><?= $message ?></div><?php endif; ?>
<div class="admin-card"><div class="admin-card-header"><div><h2 class="text-sm font-bold text-red-900">All Announcements</h2><p class="text-xs text-red-700"><?= $totalAnn ?> total announcement<?= $totalAnn!==1?'s':'' ?></p></div></div>
<?php if($result && $result->num_rows>0): while($row=$result->fetch_assoc()): $content=cleanDescription($row['content']); $img_path=!empty($row['image'])?'serve_announcement_image.php?img='.urlencode(basename($row['image'])):''; ?>
<div class="ann-item"><div class="ann-thumb"><?php if($img_path): ?><img src="<?= htmlspecialchars($img_path) ?>" alt=""><?php else: ?><i class="fas fa-bullhorn text-gray-300"></i><?php endif; ?></div><div class="flex-1 min-w-0"><div class="flex items-start justify-between gap-2"><div><div class="flex items-center gap-2"><span class="font-semibold text-gray-900 text-sm"><?= htmlspecialchars($row['title']) ?></span><span class="badge <?= $row['status']==='published'?'badge-published':'badge-draft' ?>"><?= ucfirst($row['status']) ?></span></div><p class="text-xs text-gray-500 mt-1"><?= htmlspecialchars(strlen($content)>150?substr($content,0,150).'…':$content) ?></p></div><form method="POST" onsubmit="return confirm('Delete this announcement?');"><input type="hidden" name="action" value="delete_announcement"><input type="hidden" name="announcement_id" value="<?= (int)$row['id'] ?>"><button class="px-3 py-1 text-xs rounded-lg bg-red-50 text-red-700 border border-red-200">Delete</button></form></div></div></div>
<?php endwhile; else: ?><div class="text-center py-12 text-gray-400">No announcements yet.</div><?php endif; ?>
</div></div></main>
<div id="announcementModal" class="fixed inset-0 bg-slate-900/55 backdrop-blur-sm hidden items-center justify-center p-4 z-50"><div class="bg-white rounded-2xl w-full max-w-2xl overflow-hidden"><div class="px-6 py-4 border-b bg-red-50 border-red-100 flex justify-between items-center"><h3 class="font-bold text-gray-900 text-sm">Create Announcement</h3><button id="closeModalBtn" class="w-8 h-8 rounded-lg bg-gray-100">×</button></div><div class="p-5"><form method="POST" enctype="multipart/form-data"><input type="hidden" name="action" value="add_announcement"><div class="space-y-3"><input type="text" name="title" required class="form-input" placeholder="Title"><textarea name="content" rows="5" required class="form-input" placeholder="Content"></textarea><div class="grid grid-cols-2 gap-3"><select name="status" class="form-input"><option value="draft">Draft</option><option value="published">Published</option></select><input type="file" name="announcement_image" class="form-input"></div></div><div class="mt-5 flex justify-end"><button class="btn-primary">Create Announcement</button></div></form></div></div></div>
<script>
const m=document.getElementById('announcementModal');document.getElementById('addAnnouncementBtn').addEventListener('click',()=>{m.classList.remove('hidden');m.classList.add('flex');});document.getElementById('closeModalBtn').addEventListener('click',()=>{m.classList.add('hidden');m.classList.remove('flex');});m.addEventListener('click',e=>{if(e.target===m){m.classList.add('hidden');m.classList.remove('flex');}});
</script></body></html>
