<?php
declare(strict_types=1);
session_start();
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) { header('Location: al_login.php'); exit(); }
require_once __DIR__ . '/db_config.php';
$conn = getDBConnection(); $conn->query("SET time_zone = '+08:00'");
$conn->query("CREATE TABLE IF NOT EXISTS events (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,type VARCHAR(100) DEFAULT 'General',description TEXT NULL,event_date DATETIME NOT NULL,end_date DATETIME NULL,venue VARCHAR(255) NULL,location VARCHAR(255) NULL,audience VARCHAR(120) NULL,status VARCHAR(30) DEFAULT 'published',archived TINYINT(1) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$message='';$messageType='success';
if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['action'])) {
    if ($_POST['action']==='add_event' || $_POST['action']==='update_event') {
        $id=(int)($_POST['event_id']??0);$title=trim((string)($_POST['title']??''));$type=trim((string)($_POST['type']??'General'));$desc=trim((string)($_POST['description']??''));$eventDate=trim((string)($_POST['event_date']??''));$end=trim((string)($_POST['end_date']??''));$venue=trim((string)($_POST['venue']??''));$aud=trim((string)($_POST['audience']??''));$status=trim((string)($_POST['status']??'published'));$endDate=$end!==''?$end:null;
        if ($title===''||$eventDate===''){ $message='Title and event date are required.'; $messageType='error';}
        elseif ($_POST['action']==='add_event'){ $s=$conn->prepare("INSERT INTO events (title,type,description,event_date,end_date,venue,location,audience,status,archived) VALUES (?,?,?,?,?,?,?,?,?,0)"); if($s){$s->bind_param('sssssssss',$title,$type,$desc,$eventDate,$endDate,$venue,$venue,$aud,$status);$s->execute();$s->close();$message='Event added successfully.';}}
        else { $s=$conn->prepare("UPDATE events SET title=?,type=?,description=?,event_date=?,end_date=?,venue=?,location=?,audience=?,status=? WHERE id=?"); if($s){$s->bind_param('sssssssssi',$title,$type,$desc,$eventDate,$endDate,$venue,$venue,$aud,$status,$id);$s->execute();$s->close();$message='Event updated successfully.';}}
    }
    if ($_POST['action']==='archive_event'){ $id=(int)($_POST['event_id']??0); $s=$conn->prepare("UPDATE events SET archived=1 WHERE id=?"); if($s){$s->bind_param('i',$id);$s->execute();$s->close();$message='Event archived.';}}
}
$events=[];$r=$conn->query("SELECT * FROM events WHERE COALESCE(archived,0)=0 ORDER BY event_date DESC,id DESC"); if($r){while($x=$r->fetch_assoc())$events[]=$x;}
$totalEvents=(int)($conn->query("SELECT COUNT(*) c FROM events WHERE COALESCE(archived,0)=0")->fetch_assoc()['c']??0);
$upcomingEvents=(int)($conn->query("SELECT COUNT(*) c FROM events WHERE COALESCE(archived,0)=0 AND event_date>=NOW()")->fetch_assoc()['c']??0);
$publishedEvents=(int)($conn->query("SELECT COUNT(*) c FROM events WHERE COALESCE(archived,0)=0 AND status='published'")->fetch_assoc()['c']??0);
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Events Management - Admin Panel</title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link href="https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;600;700&display=swap" rel="stylesheet"><style>
:root{--cr:#8b0000;--cr-dk:#600000;--cr-lt:#b91c1c;--cr-pale:#fef2f2;--border:#e8dada;--surface:#fff;--bg:#faf7f7;--muted:#7a6a6a;--ink:#1a0a0a;--shadow-sm:0 1px 4px rgba(139,0,0,.07),0 2px 12px rgba(139,0,0,.05);--r:14px}body{background:var(--bg);font-family:'Sora',sans-serif;color:var(--ink)}.page-title h1{font-size:1.5rem;font-weight:700;color:var(--ink);line-height:1.2}.page-title p{font-size:.82rem;color:var(--muted);margin-top:2px}.stat-pill{background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;padding:.75rem 1.25rem;color:var(--ink)}.admin-card{background:var(--surface);border-radius:var(--r);border:1px solid var(--border);box-shadow:var(--shadow-sm);overflow:hidden}.admin-card-header{background:linear-gradient(to right,#fff5f5,#ffe4e4);border-bottom:1px solid #fecaca;padding:1rem 1.5rem;display:flex;align-items:center;gap:.75rem}.form-input{border:1.5px solid #d1d5db;border-radius:100px;padding:.5rem .85rem;font-size:.82rem;width:100%;background:#fafafa}.form-input:focus{outline:none;border-color:var(--cr);box-shadow:0 0 0 3px rgba(139,0,0,.08);background:#fff}.btn-primary{background:var(--cr);color:#fff;border:none;padding:.5rem 1.15rem;border-radius:100px;font-size:.8rem;font-weight:600}.events-table{width:100%;border-collapse:collapse}.events-table thead{background:#f9fafb}.events-table th{padding:.75rem 1rem;text-align:left;font-size:.65rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:var(--muted);border-bottom:1px solid var(--border)}.events-table td{padding:.9rem 1rem;border-bottom:1px solid rgba(232,218,218,.5)}.events-table tbody tr:hover{background:var(--cr-pale)}.btn-edit,.btn-archive{border-radius:100px;font-size:.72rem;font-weight:600}.btn-edit{background:#eff6ff;color:#2563eb;border:1px solid #bfdbfe;padding:.35rem .75rem}.btn-archive{background:#fff7ed;color:#c2410c;border:1px solid #fed7aa;padding:.35rem .75rem}.badge{display:inline-flex;gap:.25rem;padding:.22rem .6rem;border-radius:9999px;font-size:.65rem;font-weight:700}.badge-published{background:#dcfce7;color:#15803d}.badge-draft{background:#fef9c3;color:#a16207}.badge-cancelled{background:#fee2e2;color:#dc2626}.event-dot{width:8px;height:8px;border-radius:50%;display:inline-block}.dot-upcoming{background:#7a0000}.dot-past{background:#9ca3af}
</style></head><body>
<?php include __DIR__ . '/ad_header_universal.php'; ?><?php include __DIR__ . '/ad_sidebar_universal.php'; ?>
<main class="pt-20 ml-16 min-h-screen"><div class="max-w-7xl mx-auto px-4 mb-5"><div class="page-title"><h1>Events</h1><p>Create and manage alumni events and activities</p></div><div class="grid grid-cols-3 gap-3 mt-4"><div class="stat-pill"><div class="text-2xl font-bold"><?= $totalEvents ?></div><div class="text-xs text-gray-500">Total Events</div></div><div class="stat-pill"><div class="text-2xl font-bold"><?= $upcomingEvents ?></div><div class="text-xs text-gray-500">Upcoming</div></div><div class="stat-pill"><div class="text-2xl font-bold"><?= $publishedEvents ?></div><div class="text-xs text-gray-500">Published</div></div></div></div>
<div class="max-w-7xl mx-auto px-4 pb-10"><?php if($message!==''): ?><div class="mb-5 px-4 py-2 rounded-lg border <?= $messageType==='success'?'bg-green-50 border-green-200 text-green-700':'bg-red-50 border-red-200 text-red-700' ?>"><?= htmlspecialchars($message) ?></div><?php endif; ?>
<div class="admin-card mb-6"><div class="admin-card-header"><div class="w-8 h-8 bg-red-800 rounded-lg flex items-center justify-center"><i class="fas fa-plus text-white text-xs"></i></div><div><h2 class="text-sm font-bold text-red-900">Add New Event</h2><p class="text-xs text-red-700">Fill in the details below to create a new event</p></div></div><div class="p-5"><form method="POST"><input type="hidden" name="action" value="add_event"><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><input name="title" required class="form-input" placeholder="Event title"><input name="type" class="form-input" placeholder="Event type"><input type="datetime-local" name="event_date" required class="form-input"><input type="datetime-local" name="end_date" class="form-input"><input name="venue" class="form-input" placeholder="Venue"><select name="status" class="form-input"><option value="published">Published</option><option value="draft">Draft</option><option value="cancelled">Cancelled</option></select><input name="audience" class="form-input md:col-span-2" placeholder="Target audience"><textarea name="description" rows="3" class="form-input md:col-span-2" placeholder="Description"></textarea></div><div class="mt-4 flex justify-end"><button class="btn-primary"><i class="fas fa-save mr-1"></i>Save Event</button></div></form></div></div>
<div class="admin-card"><div class="overflow-x-auto"><table class="events-table"><thead><tr><th>Event</th><th>Date</th><th>Venue</th><th>Audience</th><th>Status</th><th style="text-align:right">Actions</th></tr></thead><tbody><?php if(empty($events)): ?><tr><td colspan="6" class="text-center py-10 text-gray-400">No events yet</td></tr><?php else: foreach($events as $e): $up=!empty($e['event_date']) && strtotime($e['event_date'])>=time(); $st=(string)($e['status']??'published'); $bc=$st==='published'?'badge-published':($st==='draft'?'badge-draft':'badge-cancelled'); ?><tr><td><div class="flex items-start gap-2"><span class="event-dot mt-2 <?= $up?'dot-upcoming':'dot-past' ?>"></span><div><div class="font-semibold text-gray-900 text-sm"><?= htmlspecialchars((string)$e['title']) ?></div><div class="text-xs text-gray-500"><?= htmlspecialchars((string)($e['type']??'General')) ?></div></div></div></td><td><?= !empty($e['event_date'])?date('M d, Y h:i A',strtotime($e['event_date'])):'N/A' ?></td><td><?= htmlspecialchars((string)($e['venue']??$e['location']??'—')) ?></td><td><?= htmlspecialchars((string)($e['audience']??'All')) ?></td><td><span class="badge <?= $bc ?>"><?= ucfirst($st) ?></span></td><td style="text-align:right"><form method="POST" style="display:inline"><input type="hidden" name="action" value="archive_event"><input type="hidden" name="event_id" value="<?= (int)$e['id'] ?>"><button class="btn-archive"><i class="fas fa-archive mr-1"></i>Archive</button></form></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div></main></body></html>
