/** Ionicons names used across the alumni app (outline = inactive, filled optional). */
export const ICONS = {
  home: "home-outline",
  homeActive: "home",
  directory: "people-outline",
  directoryActive: "people",
  events: "calendar-outline",
  eventsActive: "calendar",
  messages: "chatbubbles-outline",
  messagesActive: "chatbubbles",
  notifications: "notifications-outline",
  jobApplications: "briefcase-outline",
  upcomingEvents: "calendar-outline",
  career: "briefcase-outline",
  myCareer: "trending-up-outline",
  alumniCard: "card-outline",
  about: "school-outline",
  faqs: "help-circle-outline",
  profile: "person-outline",
  editProfile: "create-outline",
  logout: "log-out-outline",
  privacy: "lock-closed-outline",
  pushNotifications: "notifications-outline",
  search: "search-outline",
  add: "add",
  close: "close",
  back: "chevron-back",
  location: "location-outline",
  time: "time-outline",
  megaphone: "megaphone-outline",
  checkmark: "checkmark-circle",
  apply: "paper-plane-outline",
  menu: "menu-outline",
  chevronForward: "chevron-forward",
};
